name: coach_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn=1.1.3
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipykernel
  - pytest
  - black
  - flake8
  - mypy
  - dash
  - dash-bootstrap-components
  - plotly
  - opencv
  - pillow
  - tqdm
  - statsmodels
  - selenium
  - tabulate
  - pip
  - pip:
    - nba_api
    - requests
    - streamlit
    - xgboost
    - lightgbm
    - shap
    - beautifulsoup4
    - cpi==1.1.2
    - lxml
    - ipython