name: Daily NBA Data Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-nba-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .devcontainer/requirements.txt

      - name: Run NBA data update script
        run: python src/main.py --debug

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/processed/nba_player_data_final_inflated.csv
          git add data/processed/salary_cap_history_inflated.csv
          git commit -m "Update NBA data" || exit 0
          git push