name: Update Data Daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.5
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.5"
        architecture: "x64"  # This specifies the architecture
        cache: "pip"  # Caching pip dependencies for faster builds

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run data update module
      run: python -m src.salary_predict.data_loader_preprocessor

    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: data-processing-log
        path: data_processing.log

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Automated data update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
